
version: "3.7"

services:

  mysql:
      image: mysql:5.7
      volumes:
        - mysql-data:/var/lib/mysql
      ports:
        - 3306:3306
      environment:
        - MYSQL_DATABASE=cpchain_django
        - MYSQL_ROOT_PASSWORD=cpchain
        - LANG=C.UTF-8
      command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --skip-character-set-client-handshake

volumes:
  mysql-data:
    external: false
  