version: 2.0

# heavily inspired by https://raw.githubusercontent.com/pinax/pinax-wiki/6bd2a99ab6f702e300d708532a6d1d9aa638b9f8/.circleci/config.yml

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        keys:
          - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: run tox
        command: ~/.local/bin/tox -r
    - save_cache:
        paths:
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
          - ~/.ethash
          - ~/.py-geth
        key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

parity_steps: &parity_steps
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        keys:
          - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: install parity if needed
        command: |
          pip install --user requests eth_utils tqdm eth-hash[pycryptodome]
          echo "Job specifies Parity version $PARITY_VERSION"
          python tests/integration/parity/install_parity.py $PARITY_VERSION
    - run:
        name: update parity deps from testing repo if needed
        command: |
          [ "`cat /etc/*release | grep jessie`" != "" ] && echo "On Jessie - installing missing deps..." || echo "Not on Jessie - doing nothing."
          [ "`cat /etc/*release | grep jessie`" != "" ] || exit 0
          echo "deb http://ftp.debian.org/debian testing main" > testing.list && sudo mv testing.list /etc/apt/sources.list.d/
          sudo apt update
          sudo apt-get -t testing install libstdc++6
    - run:
        name: run tox
        command: ~/.local/bin/tox -r
    - save_cache:
        paths:
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
          - ~/.ethash
          - ~/.py-geth
          - ~/.parity-bin
        key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

geth_steps: &geth_steps
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        keys:
          - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: build geth if missing
        command: |
          mkdir -p $HOME/.ethash
          pip install --user py-geth>=1.10.1
          export GOROOT=/usr/local/go
          export GETH_BINARY="$HOME/.py-geth/geth-$GETH_VERSION/bin/geth"
          if [ ! -e "$GETH_BINARY" ]; then
            curl -O https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz
            tar xvf go1.7.4.linux-amd64.tar.gz
            sudo chown -R root:root ./go
            sudo mv go /usr/local
            sudo ln -s /usr/local/go/bin/go /usr/local/bin/go
            sudo apt-get update;
            sudo apt-get install -y build-essential;
            python -m geth.install $GETH_VERSION;
          fi
          sudo ln -s /home/circleci/.py-geth/geth-$GETH_VERSION/bin/geth /usr/local/bin/geth
          geth version
          geth makedag 0 $HOME/.ethash
    - run:
        name: run tox
        command: ~/.local/bin/tox -r
    - save_cache:
        paths:
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
          - ~/.ethash
          - ~/.py-geth
        key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}


jobs:
  #
  # Python 3.5
  #
  py35-core:
    <<: *common
    docker:
      - image: circleci/python:3.5
    environment:
      TOXENV: py35-core

  py35-core-eth_abi2:
    <<: *common
    docker:
      - image: circleci/python:3.5
    environment:
      TOXENV: py35-core-eth_abi2

  py35-ens:
    <<: *common
    docker:
      - image: circleci/python:3.5
    environment:
      TOXENV: py35-ens

  py35-integration-goethereum-ipc-1.7.2:
    <<: *geth_steps
    docker:
      - image: circleci/python:3.5
    environment:
      TOXENV: py35-integration-goethereum-ipc
      GETH_VERSION: v1.7.2

  py35-integration-goethereum-http-1.7.2:
    <<: *geth_steps
    docker:
      - image: circleci/python:3.5
    environment:
      TOXENV: py35-integration-goethereum-http
      GETH_VERSION: v1.7.2

  py35-integration-goethereum-ws-1.7.2:
    <<: *geth_steps
    docker:
      - image: circleci/python:3.5
    environment:
      TOXENV: py35-integration-goethereum-ws
      GETH_VERSION: v1.7.2

  py35-integration-goethereum-ipc-1.8.1:
    <<: *geth_steps
    docker:
      - image: circleci/python:3.5
    environment:
      TOXENV: py35-integration-goethereum-ipc
      GETH_VERSION: v1.8.1

  py35-integration-goethereum-http-1.8.1:
    <<: *geth_steps
    docker:
      - image: circleci/python:3.5
    environment:
      TOXENV: py35-integration-goethereum-http
      GETH_VERSION: v1.8.1

  py35-integration-goethereum-ws-1.8.1:
    <<: *geth_steps
    docker:
      - image: circleci/python:3.5
    environment:
      TOXENV: py35-integration-goethereum-ws
      GETH_VERSION: v1.8.1

  py35-integration-parity-ipc:
    <<: *parity_steps
    docker:
      - image: circleci/python:3.5-jessie
    environment:
      TOXENV: py35-integration-parity-ipc
      PARITY_VERSION: v1.11.11
      PARITY_OS: debian

  py35-integration-parity-http:
    <<: *parity_steps
    docker:
      - image: circleci/python:3.5-jessie
    environment:
      TOXENV: py35-integration-parity-http
      PARITY_VERSION: v1.11.11
      PARITY_OS: debian

  py35-integration-parity-ws:
    <<: *parity_steps
    docker:
      - image: circleci/python:3.5-jessie
    environment:
      TOXENV: py35-integration-parity-ws
      PARITY_VERSION: v1.11.11
      PARITY_OS: debian

  py35-integration-ethtester-pyevm:
    <<: *common
    docker:
      - image: circleci/python:3.5
    environment:
      TOXENV: py35-integration-ethtester
      ETHEREUM_TESTER_CHAIN_BACKEND: eth_tester.backends.PyEVMBackend
  #
  # Python 3.6
  #
  lint:
    <<: *common
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: lint

  doctest:
    <<: *common
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: doctest

  py36-core:
    <<: *common
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36-core

  py36-core-eth_abi2:
    <<: *common
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36-core-eth_abi2

  py36-ens:
    <<: *common
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36-ens

  py36-integration-goethereum-ipc-1.7.2:
    <<: *geth_steps
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36-integration-goethereum-ipc
      GETH_VERSION: v1.7.2

  py36-integration-goethereum-http-1.7.2:
    <<: *geth_steps
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36-integration-goethereum-http
      GETH_VERSION: v1.7.2

  py36-integration-goethereum-ws-1.7.2:
    <<: *geth_steps
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36-integration-goethereum-ws
      GETH_VERSION: v1.7.2

  py36-integration-goethereum-ipc-1.8.1:
    <<: *geth_steps
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36-integration-goethereum-ipc
      GETH_VERSION: v1.8.1

  py36-integration-goethereum-http-1.8.1:
    <<: *geth_steps
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36-integration-goethereum-http
      GETH_VERSION: v1.8.1

  py36-integration-goethereum-ws-1.8.1:
    <<: *geth_steps
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36-integration-goethereum-ws
      GETH_VERSION: v1.8.1

  py36-integration-parity-ipc:
    <<: *parity_steps
    docker:
      - image: circleci/python:3.6-stretch
    environment:
      TOXENV: py36-integration-parity-ipc
      PARITY_VERSION: v1.11.11
      PARITY_OS: debian

  py36-integration-parity-http:
    <<: *parity_steps
    docker:
      - image: circleci/python:3.6-stretch
    environment:
      TOXENV: py36-integration-parity-http
      PARITY_VERSION: v1.11.11
      PARITY_OS: debian

  py36-integration-parity-ws:
    <<: *parity_steps
    docker:
      - image: circleci/python:3.6-stretch
    environment:
      TOXENV: py36-integration-parity-ws
      PARITY_VERSION: v1.11.11
      PARITY_OS: debian

  py36-integration-ethtester-pyevm:
    <<: *common
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36-integration-ethtester
      ETHEREUM_TESTER_CHAIN_BACKEND: eth_tester.backends.PyEVMBackend
  #
  # Python 3.7
  #
  py37-core:
    <<: *common
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37-core

  py37-core-eth_abi2:
    <<: *common
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37-core-eth_abi2

  py37-ens:
    <<: *common
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37-ens

  py37-integration-goethereum-ipc-1.7.2:
    <<: *geth_steps
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37-integration-goethereum-ipc
      GETH_VERSION: v1.7.2

  py37-integration-goethereum-http-1.7.2:
    <<: *geth_steps
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37-integration-goethereum-http
      GETH_VERSION: v1.7.2

  py37-integration-goethereum-ws-1.7.2:
    <<: *geth_steps
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37-integration-goethereum-ws
      GETH_VERSION: v1.7.2

  py37-integration-goethereum-ipc-1.8.1:
    <<: *geth_steps
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37-integration-goethereum-ipc
      GETH_VERSION: v1.8.1

  py37-integration-goethereum-http-1.8.1:
    <<: *geth_steps
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37-integration-goethereum-http
      GETH_VERSION: v1.8.1

  py37-integration-goethereum-ws-1.8.1:
    <<: *geth_steps
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37-integration-goethereum-ws
      GETH_VERSION: v1.8.1

  py37-integration-parity-ipc:
    <<: *parity_steps
    docker:
      - image: circleci/python:3.7-stretch
    environment:
      TOXENV: py37-integration-parity-ipc
      PARITY_VERSION: v1.11.11
      PARITY_OS: debian

  py37-integration-parity-http:
    <<: *parity_steps
    docker:
      - image: circleci/python:3.7-stretch
    environment:
      TOXENV: py37-integration-parity-http
      PARITY_VERSION: v1.11.11
      PARITY_OS: debian

  py37-integration-parity-ws:
    <<: *parity_steps
    docker:
      - image: circleci/python:3.7-stretch
    environment:
      TOXENV: py37-integration-parity-ws
      PARITY_VERSION: v1.11.11
      PARITY_OS: debian

  py37-integration-ethtester-pyevm:
    <<: *common
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37-integration-ethtester
      ETHEREUM_TESTER_CHAIN_BACKEND: eth_tester.backends.PyEVMBackend

workflows:
  version: 2
  test:
    jobs:
      - lint
      - doctest
      - py35-core-eth_abi2
      - py35-core
      - py35-ens
      - py35-integration-goethereum-ipc-1.7.2
      - py35-integration-goethereum-http-1.7.2
      - py35-integration-goethereum-ws-1.7.2
      - py35-integration-goethereum-ipc-1.8.1
      - py35-integration-goethereum-http-1.8.1
      - py35-integration-goethereum-ws-1.8.1
      - py35-integration-parity-ipc
      - py35-integration-parity-http
      - py35-integration-parity-ws
      - py35-integration-ethtester-pyevm
      - py36-core-eth_abi2
      - py36-core
      - py36-ens
      - py36-integration-goethereum-ipc-1.7.2
      - py36-integration-goethereum-http-1.7.2
      - py36-integration-goethereum-ws-1.7.2
      - py36-integration-goethereum-ipc-1.8.1
      - py36-integration-goethereum-http-1.8.1
      - py36-integration-goethereum-ws-1.8.1
      - py36-integration-parity-ipc
      - py36-integration-parity-http
      - py36-integration-parity-ws
      - py36-integration-ethtester-pyevm
      - py37-core-eth_abi2
      - py37-core
      - py37-ens
      - py37-integration-goethereum-ipc-1.7.2
      - py37-integration-goethereum-http-1.7.2
      - py37-integration-goethereum-ws-1.7.2
      - py37-integration-goethereum-ipc-1.8.1
      - py37-integration-goethereum-http-1.8.1
      - py37-integration-goethereum-ws-1.8.1
      - py37-integration-parity-ipc
      - py37-integration-parity-http
      - py37-integration-parity-ws
      - py37-integration-ethtester-pyevm
