# Generated by Django 2.2.2 on 2020-12-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='name',
            field=models.CharField(help_text='模板名称', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='templates',
            name='type_id',
            field=models.IntegerField(help_text='模板类型 ID', null=True),
        ),
    ]
