# Generated by Django 2.2.2 on 2020-07-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(help_text='ip', max_length=100)),
                ('latitude', models.FloatField(help_text='latitude/纬度')),
                ('longitude', models.FloatField(help_text='longitude/经度')),
                ('handled', models.BooleanField(default=False, help_text='是否已处理，即获取到经纬度')),
                ('deleted', models.BooleanField(default=False, help_text='是否已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
