# Generated by Django 2.2.2 on 2020-07-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_ip', '0002_auto_20200714_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.GenericIPAddressField(help_text='ip', unique=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='latitude',
            field=models.FloatField(help_text='latitude/纬度', null=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='longitude',
            field=models.FloatField(help_text='longitude/经度', null=True),
        ),
    ]
