# Generated by Django 2.1.2 on 2019-06-17 06:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Community Updates', 'Community Updates'), ('Community Events', 'Community Events'), ('Official Announcement', 'Official Announcement'), ('项目进展', '项目进展'), ('重大发布', '重大发布'), ('draft', 'draft')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='img/News')),
                ('update_time', models.DateField()),
                ('summary', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
            ],
        ),
    ]
