# Generated by Django 2.1.2 on 2019-06-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='summary',
        ),
    ]
