# Generated by Django 2.1.2 on 2019-06-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20190617_1441'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallet',
            new_name='WalletNews',
        ),
    ]
