# Generated by Django 2.2.2 on 2021-02-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressMark',
        ),
        migrations.DeleteModel(
            name='AddressMarkType',
        ),
    ]
