config = {'abi': [
    {'constant': True, 'inputs': [], 'name': 'termLen', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False,
     'stateMutability': 'view', 'type': 'function'},
    {'constant': True, 'inputs': [{'name': '_termIdx', 'type': 'uint256'}], 'name': 'candidatesOf',
     'outputs': [{'name': '', 'type': 'address[]'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'},
    {'constant': False,
     'inputs': [{'name': '_numOfCampaign', 'type': 'uint256'}, {'name': '_cpuNonce', 'type': 'uint64'},
                {'name': '_cpuBlockNumber', 'type': 'uint256'}, {'name': '_memoryNonce', 'type': 'uint64'},
                {'name': '_memoryBlockNumber', 'type': 'uint256'}, {'name': 'version', 'type': 'uint256'}],
     'name': 'claimCampaign', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
    {'constant': True, 'inputs': [], 'name': 'termIdx', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False,
     'stateMutability': 'view', 'type': 'function'},
    {'constant': True, 'inputs': [], 'name': 'minNoc', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False,
     'stateMutability': 'view', 'type': 'function'},
    {'constant': True, 'inputs': [], 'name': 'numPerRound', 'outputs': [{'name': '', 'type': 'uint256'}],
     'payable': False, 'stateMutability': 'view', 'type': 'function'},
    {'constant': True, 'inputs': [], 'name': 'viewLen', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False,
     'stateMutability': 'view', 'type': 'function'},
    {'constant': True, 'inputs': [], 'name': 'updatedTermIdx', 'outputs': [{'name': '', 'type': 'uint256'}],
     'payable': False, 'stateMutability': 'view', 'type': 'function'},
    {'constant': False, 'inputs': [{'name': '_supportedVersion', 'type': 'uint256'}], 'name': 'updateSupportedVersion',
     'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
    {'constant': False, 'inputs': [{'name': '_maxNoc', 'type': 'uint256'}], 'name': 'updateMaxNoc', 'outputs': [],
     'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
    {'constant': False, 'inputs': [{'name': '_minNoc', 'type': 'uint256'}], 'name': 'updateMinNoc', 'outputs': [],
     'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
    {'constant': True, 'inputs': [], 'name': 'acceptableBlocks', 'outputs': [{'name': '', 'type': 'uint256'}],
     'payable': False, 'stateMutability': 'view', 'type': 'function'},
    {'constant': False, 'inputs': [{'name': '_addr', 'type': 'address'}], 'name': 'setAdmissionAddr', 'outputs': [],
     'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
    {'constant': False, 'inputs': [{'name': '_termLen', 'type': 'uint256'}], 'name': 'updateTermLen', 'outputs': [],
     'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
    {'constant': False, 'inputs': [{'name': '_viewLen', 'type': 'uint256'}], 'name': 'updateViewLen', 'outputs': [],
     'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
    {'constant': True, 'inputs': [], 'name': 'supportedVersion', 'outputs': [{'name': '', 'type': 'uint256'}],
     'payable': False, 'stateMutability': 'view', 'type': 'function'},
    {'constant': False, 'inputs': [{'name': '_acceptableBlocks', 'type': 'uint256'}], 'name': 'updateAcceptableBlocks',
     'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
    {'constant': True, 'inputs': [{'name': '_candidate', 'type': 'address'}], 'name': 'candidateInfoOf',
     'outputs': [{'name': '', 'type': 'uint256'}, {'name': '', 'type': 'uint256'}, {'name': '', 'type': 'uint256'}],
     'payable': False, 'stateMutability': 'view', 'type': 'function'},
    {'constant': True, 'inputs': [], 'name': 'maxNoc', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False,
     'stateMutability': 'view', 'type': 'function'},
    {'constant': False, 'inputs': [{'name': '_addr', 'type': 'address'}], 'name': 'setRnodeInterface', 'outputs': [],
     'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
    {'inputs': [{'name': '_admissionAddr', 'type': 'address'}, {'name': '_rnodeAddr', 'type': 'address'}],
     'payable': False, 'stateMutability': 'nonpayable', 'type': 'constructor'},
    {'payable': True, 'stateMutability': 'payable', 'type': 'fallback'}, {'anonymous': False, 'inputs': [
        {'indexed': False, 'name': 'candidate', 'type': 'address'},
        {'indexed': False, 'name': 'startTermIdx', 'type': 'uint256'},
        {'indexed': False, 'name': 'stopTermIdx', 'type': 'uint256'}], 'name': 'ClaimCampaign', 'type': 'event'}]}
# address = "0x20BF49A0773a2b9eA5cF218C188d7F633b07c267"



