config = {'abi': [
    {'constant': True, 'inputs': [], 'name': 'termLen', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False,
     'stateMutability': 'view', 'type': 'function'},
    {'constant': True, 'inputs': [{'name': '_termIdx', 'type': 'uint256'}], 'name': 'candidatesOf',
     'outputs': [{'name': '', 'type': 'address[]'}], 'payable': False, 'stateMutability': 'view', 'type': 'function'},
    {'constant': False,
     'inputs': [{'name': '_numOfCampaign', 'type': 'uint256'}, {'name': '_cpuNonce', 'type': 'uint64'},
                {'name': '_cpuBlockNumber', 'type': 'uint256'}, {'name': '_memoryNonce', 'type': 'uint64'},
                {'name': '_memoryBlockNumber', 'type': 'uint256'}, {'name': 'version', 'type': 'uint256'}],
     'name': 'claimCampaign', 'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
    {'constant': True, 'inputs': [], 'name': 'termIdx', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False,
     'stateMutability': 'view', 'type': 'function'},
    {'constant': True, 'inputs': [], 'name': 'minNoc', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False,
     'stateMutability': 'view', 'type': 'function'},
    {'constant': True, 'inputs': [], 'name': 'numPerRound', 'outputs': [{'name': '', 'type': 'uint256'}],
     'payable': False, 'stateMutability': 'view', 'type': 'function'},
    {'constant': True, 'inputs': [], 'name': 'viewLen', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False,
     'stateMutability': 'view', 'type': 'function'},
    {'constant': True, 'inputs': [], 'name': 'updatedTermIdx', 'outputs': [{'name': '', 'type': 'uint256'}],
     'payable': False, 'stateMutability': 'view', 'type': 'function'},
    {'constant': False, 'inputs': [{'name': '_supportedVersion', 'type': 'uint256'}], 'name': 'updateSupportedVersion',
     'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
    {'constant': False, 'inputs': [{'name': '_maxNoc', 'type': 'uint256'}], 'name': 'updateMaxNoc', 'outputs': [],
     'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
    {'constant': False, 'inputs': [{'name': '_minNoc', 'type': 'uint256'}], 'name': 'updateMinNoc', 'outputs': [],
     'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
    {'constant': True, 'inputs': [], 'name': 'acceptableBlocks', 'outputs': [{'name': '', 'type': 'uint256'}],
     'payable': False, 'stateMutability': 'view', 'type': 'function'},
    {'constant': False, 'inputs': [{'name': '_addr', 'type': 'address'}], 'name': 'setAdmissionAddr', 'outputs': [],
     'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
    {'constant': False, 'inputs': [{'name': '_termLen', 'type': 'uint256'}], 'name': 'updateTermLen', 'outputs': [],
     'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
    {'constant': False, 'inputs': [{'name': '_viewLen', 'type': 'uint256'}], 'name': 'updateViewLen', 'outputs': [],
     'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
    {'constant': True, 'inputs': [], 'name': 'supportedVersion', 'outputs': [{'name': '', 'type': 'uint256'}],
     'payable': False, 'stateMutability': 'view', 'type': 'function'},
    {'constant': False, 'inputs': [{'name': '_acceptableBlocks', 'type': 'uint256'}], 'name': 'updateAcceptableBlocks',
     'outputs': [], 'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
    {'constant': True, 'inputs': [{'name': '_candidate', 'type': 'address'}], 'name': 'candidateInfoOf',
     'outputs': [{'name': '', 'type': 'uint256'}, {'name': '', 'type': 'uint256'}, {'name': '', 'type': 'uint256'}],
     'payable': False, 'stateMutability': 'view', 'type': 'function'},
    {'constant': True, 'inputs': [], 'name': 'maxNoc', 'outputs': [{'name': '', 'type': 'uint256'}], 'payable': False,
     'stateMutability': 'view', 'type': 'function'},
    {'constant': False, 'inputs': [{'name': '_addr', 'type': 'address'}], 'name': 'setRnodeInterface', 'outputs': [],
     'payable': False, 'stateMutability': 'nonpayable', 'type': 'function'},
    {'inputs': [{'name': '_admissionAddr', 'type': 'address'}, {'name': '_rnodeAddr', 'type': 'address'}],
     'payable': False, 'stateMutability': 'nonpayable', 'type': 'constructor'},
    {'payable': True, 'stateMutability': 'payable', 'type': 'fallback'}, {'anonymous': False, 'inputs': [
        {'indexed': False, 'name': 'candidate', 'type': 'address'},
        {'indexed': False, 'name': 'startTermIdx', 'type': 'uint256'},
        {'indexed': False, 'name': 'stopTermIdx', 'type': 'uint256'}], 'name': 'ClaimCampaign', 'type': 'event'}]}
# address = "0x20BF49A0773a2b9eA5cF218C188d7F633b07c267"
ours = ['0x27c3500c8a493a152f1dfdec162c422b3678b03e',
        '0xf285996f36aa76adf637c60f2005da637efd71aa',
        '0x50bf9d407d8e30b8124f3711df97611d76d45699',
        '0x99fc3138ff48a4fae3a0e65c6f83266a5284a683',
        '0xf6f59e901b3cd551f1753dfe80ab806bb0046b30',
        '0xa3a0fe044eb8ce1731ed99ca0901a795abf58da8',
        '0x45f40e0c7135d86d92a88443a160045a2897436e',
        '0x0005efc08c5ff71c3538ebc85b1bb93c377cef14',
        '0x46ac4607b5334b5dc7cd671b0c11c5ffa81324f6',
        '0x1573ce2ab9a0113d25ce5e7a74b564a02f9058ad',
        '0x01cf3229840fc212d54df720cdae3e6d04320a9c',
        '0xaa8ad61eb978bbde0b6f69d2cd3033755d8f9d04', ]
