# Generated by Django 2.2.2 on 2021-02-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='handled',
            field=models.BooleanField(default=False, help_text='是否已处理', null=True),
        ),
    ]
