# Generated by Django 2.2.2 on 2020-07-05 01:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.CharField(max_length=36)),
                ('address', models.CharField(help_text='赞同人地址', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimEmailReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Congress',
            fields=[
                ('address', models.CharField(help_text='地址', max_length=200, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='邮件内容')),
                ('to', models.CharField(help_text='收信人', max_length=50)),
                ('sent', models.BooleanField(default=False, help_text='是否发送')),
                ('sent_at', models.DateTimeField(help_text='发送时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField()),
                ('url', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProposalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zh', models.CharField(help_text='中文', max_length=50, verbose_name='中文名称')),
                ('en', models.CharField(default='', help_text='英文', max_length=50, verbose_name='English name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('amount', models.FloatField(default=0, help_text='金额(cpc)')),
                ('status', models.CharField(choices=[('available', 'available'), ('development', 'development'), ('completed', 'completed')], default='available', help_text='任务状态', max_length=30)),
                ('requirement', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VotedAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.CharField(max_length=36)),
                ('address', models.CharField(help_text='投票人地址', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('advantages', models.CharField(help_text='优势', max_length=1000)),
                ('estimated_date', models.DateField(help_text='预计完成日期', null=True, verbose_name='预计完成日期')),
                ('send_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='community.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('proposal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='提案描述', null=True)),
                ('locked_amount', models.FloatField(editable=False, help_text='金额，单位为CPC', null=True)),
                ('locked_time', models.DateTimeField(editable=False, help_text='提案时间', null=True)),
                ('period', models.IntegerField(help_text='等待时间，单位为秒', null=True)),
                ('likes', models.IntegerField(editable=False, help_text='赞同数', null=True)),
                ('votes', models.IntegerField(editable=False, help_text='投票数', null=True)),
                ('proposer_addr', models.CharField(default='', help_text='发起人地址', max_length=100)),
                ('depositor_addr', models.CharField(default='', editable=False, help_text='提案存钱人地址', max_length=100)),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('deposited', 'deposited'), ('community congress', 'community congress'), ('decision congress', 'decision congress'), ('passed', 'passed'), ('declined', 'declined'), ('timeout', 'timeout')], default='submitted', help_text='提案状态', max_length=30)),
                ('reason', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', help_text='理由-决策议会给出的结果', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='community.ProposalType')),
            ],
        ),
    ]
