# Generated by Django 2.1.2 on 2018-10-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/img/Partners')),
                ('link', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Partners', 'Partners'), ('Investors', 'Investors'), ('Exchanges', 'Exchanges')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_zh', models.CharField(blank=True, max_length=50, null=True)),
                ('job', models.CharField(max_length=50)),
                ('job_zh', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/Team')),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('desc_zh', models.CharField(blank=True, max_length=500, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Department')),
            ],
        ),
    ]
