# Generated by Django 2.1.2 on 2018-10-22 08:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
