# Generated by Django 2.1.2 on 2018-10-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20181022_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='banner',
            field=models.ImageField(default='', upload_to='static/img/News'),
        ),
        migrations.AlterField(
            model_name='new',
            name='update_time',
            field=models.DateField(),
        ),
    ]
