# Generated by Django 2.1.2 on 2018-10-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20181026_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='banner',
            field=models.ImageField(null=True, upload_to='static/img/News'),
        ),
    ]
