# Generated by Django 2.1.2 on 2018-10-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20181026_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='banner',
            field=models.ImageField(null=True, upload_to='img/News'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(upload_to='img/Partners'),
        ),
    ]
