# Generated by Django 2.1.2 on 2018-10-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20181026_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/Team'),
        ),
    ]
