# Generated by Django 2.1.2 on 2018-11-05 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20181031_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammate',
            old_name='job',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='teammate',
            old_name='job_zh',
            new_name='title_zh',
        ),
    ]
