# Generated by Django 2.1.2 on 2018-11-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20181105_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammate',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
    ]
