# Generated by Django 2.1.2 on 2018-11-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_teammate_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='image',
            field=models.ImageField(blank=True, default='static/img/profile.png', null=True, upload_to='img/Team'),
        ),
    ]
