# Generated by Django 2.1.2 on 2018-11-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20181105_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/Team'),
        ),
    ]
