# Generated by Django 2.1.2 on 2018-11-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20181105_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='img/News'),
        ),
    ]
