# Generated by Django 2.1.2 on 2018-11-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20181105_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='partner',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
